FROM openjdk:8-jdk-alpine

ADD build/libs/greetingservice-0.0.1-SNAPSHOT.jar /home/app.jar
COPY docker/application.properties /home/config/application.properties

WORKDIR /home

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
