/* Flag is true when the last git commit is done by the semantic-release tool.
*  The commit message looks like: chore(release): {version} [skip ci]
*  This means all stages can be skipped, because nothing changed, but the version in package.json.
*/
def wasLastCommitSemanticReleaseVersioningOnly = false

pipeline {
    agent {
        dockerfile {
            filename 'greeting-service/docker/dockerfile-jenkins'
            // mount the docker daemon from the host into the agent
            args '-ti -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '4'))
    }
    environment {
        GIT_REPO_NAME = GIT_URL.replaceFirst(/^.*\/([^\/]+?).git$/, '$1')
        REGISTRY = "<your-ip>:5000" // muss in /.docker/daemon.json als insecure registry stehen!
    }
    stages {
        stage("Package") {
            steps {
                dir("greeting-service") {
                    sh "chmod +x gradlew"
                    sh "./gradlew bootJar"
                }
            }
        }
        stage("Build and Push Docker Image") {
            environment {
                SHORT_BRANCH = "${shortenGitBranch()}"
                DOCKERTAG = "${REGISTRY}/greeting-service:${SHORT_BRANCH}-build.${BUILD_NUMBER}"
            }
            steps {
                dir("greeting-service") {
                    sh "docker build -t ${DOCKERTAG} -f docker/dockerfile-app ."
                    sh "docker push ${DOCKERTAG}"
                }
            }
            post {
                always {
                    sh "docker rmi ${DOCKERTAG}"
                }
            }
        }
    } // stages
    post {
        always {
            cleanWs()
        }
    }
}

// Returns the git branch without e.g. "origin/" or "feature/"
def shortenGitBranch() {
    def gitBranch = GIT_BRANCH.trim()
    if (gitBranch.contains('/')) {
        gitBranch = gitBranch.split('/').last()
    }
    return gitBranch
}
